name: EAS Update (Expo)

on:
  push:
    branches: [ "main" ]

jobs:
  eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Ensure assets directory
        run: |
          mkdir -p assets
          
          # Only download assets if they don't exist
          if [ ! -f assets/icon.png ]; then
            curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/icon.png -o assets/icon.png
          fi
          if [ ! -f assets/splash.png ]; then
            curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/splash.png -o assets/splash.png
          fi
          if [ ! -f assets/adaptive-icon.png ]; then
            curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/adaptive-icon.png -o assets/adaptive-icon.png
          fi
          if [ ! -f assets/favicon.png ]; then
            curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/favicon.png -o assets/favicon.png
          fi

      - name: Expo Login
        run: CI=1 npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
        
      - name: Initialize EAS Project
        run: npx eas init --non-interactive --force

      - name: EAS Update
        run: npx eas update --branch main --message "GitHub Action update" --non-interactive
