name: EAS Update (Expo)

on:
  push:
    branches: [ "main" ]

jobs:
  eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Latest EAS CLI
        run: npm install -g eas-cli@latest json

      - name: Update package.json for SDK 52
        run: |
          # Use SDK 52 as specified in guide section 19
          json -I -f package.json -e 'this.dependencies = this.dependencies || {}'
          json -I -f package.json -e 'this.dependencies.expo = "~52.0.0"'
          json -I -f package.json -e 'this.dependencies["react-native"] = "0.73.2"'
          json -I -f package.json -e 'this.dependencies.react = "18.2.0"'
          json -I -f package.json -e 'this.dependencies["expo-updates"] = "~0.24.0"'
          json -I -f package.json -e 'this.dependencies["react-native-safe-area-context"] = "4.6.3"'
          
          # Add Babel plugins as dev dependencies (not global)
          json -I -f package.json -e 'this.devDependencies = this.devDependencies || {}'
          json -I -f package.json -e 'this.devDependencies["@babel/plugin-transform-export-namespace-from"] = "^7.23.4"'
          json -I -f package.json -e 'this.devDependencies["babel-preset-expo"] = "~9.5.0"'

      # Create babel config with correct plugin name
      - name: Create babel.config.js
        run: |
          echo 'module.exports = function(api) {
            api.cache(true);
            return {
              presets: ["babel-preset-expo"],
              plugins: ["@babel/plugin-transform-export-namespace-from"]
            };
          };' > babel.config.js

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Create Compatible eas.json
        run: |
          echo '{
            "cli": {
              "version": ">=15.0.0"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal"
              },
              "preview": {
                "distribution": "internal"
              },
              "production": {}
            },
            "submit": {
              "production": {}
            }
          }' > eas.json

      - name: Update app.json with owner and SDK 52
        run: |
          echo '{
            "expo": {
              "name": "Time Display",
              "slug": "time-display",
              "owner": "${{ secrets.EXPO_USERNAME }}",
              "sdkVersion": "52.0.0",
              "version": "1.0.0",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#000000"
              },
              "assetBundlePatterns": [
                "**/*"
              ],
              "ios": {
                "supportsTablet": true
              },
              "android": {
                "adaptiveIcon": {
                  "foregroundImage": "./assets/adaptive-icon.png",
                  "backgroundColor": "#000000"
                }
              },
              "web": {
                "favicon": "./assets/favicon.png"
              },
              "runtimeVersion": {
                "policy": "sdkVersion"
              }
            }
          }' > app.json

      - name: Create assets directory
        run: mkdir -p assets

      - name: Download assets
        run: |
          curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/icon.png -o assets/icon.png
          curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/splash.png -o assets/splash.png
          curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/adaptive-icon.png -o assets/adaptive-icon.png
          curl -s https://raw.githubusercontent.com/expo/expo/master/templates/expo-template-blank/assets/favicon.png -o assets/favicon.png

      - name: Expo Login
        run: CI=1 npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
        
      - name: Initialize EAS Project
        run: npx eas init --non-interactive --force

      - name: EAS Update
        run: npx eas update --branch main --message "GitHub Action update" --non-interactive
